// 無指定の時にデフォルトONになるものをselected: trueにする。

exports.genres =
    [{ text: '和食', value: '0101', selected: true },
      { text: '洋食', value: '0102', selected: true },
      { text: 'バイキング', value: '0103' },
      { text: '中華', value: '0104', selected: true },
      { text: 'アジア料理、エスニック', value: '0105' },
      { text: 'ラーメン', value: '0106' },
      { text: 'カレー', value: '0107' },
      { text: '焼肉、ホルモン、ジンギスカン', value: '0108' },
      { text: '鍋', value: '0109' },
      { text: '居酒屋、ビアホール', value: '0110' },
      { text: '定食、食堂', value: '0111' },
      { text: '創作料理、無国籍料理', value: '0112' },
      { text: '自然食、薬膳、オーガニック', value: '0113' },
      { text: '持ち帰り、宅配', value: '0114' },
      { text: 'カフェ、喫茶店', value: '0115', selected: true },
      { text: 'コーヒー、茶葉専門店', value: '0116', selected: true },
      { text: 'パン、サンドイッチ', value: '0117', selected: true },
      { text: 'スイーツ', value: '0118', selected: true },
      { text: 'バー', value: '0119' },
      { text: 'パブ、スナック', value: '0120' },
      { text: 'ディスコ、クラブハウス', value: '0121' },
      { text: 'ビアガーデン', value: '0122' },
      { text: 'ファミレス、ファストフード', value: '0123' },
      { text: 'パーティー、カラオケ', value: '0124' },
      { text: '屋形船、クルージング', value: '0125' },
      { text: 'テーマパークレストラン', value: '0126' },
      { text: 'オーベルジュ', value: '0127' },
      { text: 'その他', value: '0128' }];
