name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    name: BUILD

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: "10"
      env:
        LANG: ja_JP.UTF-8
        TZ: Asia/Tokyo
    - run: |
        echo "${LANG}" , "${TZ}"
    - run: node --version
    - run: yarn install
    - run: yarn build

    - run: |
        echo "${PROJECT_ID}" , "${FIREBASE_TOKEN}"
        yarn global add firebase-tools
        `yarn global bin`/firebase --version
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
