name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    name: BUILD

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['10']

    steps:
    - uses: actions/checkout@v2
    - name: SET Env
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        LANG: ja_JP.UTF-8
        TZ: Asia/Tokyo
      run: |
        echo "${PROJECT_ID}" , "${FIREBASE_TOKEN}"
        echo "${LANG}" , "${TZ}"
    - name: install & build
      uses: actions/setup-node@v1
      with:
        node-version: "10"
    - run: node --version
    - run: yarn install
    - run: yarn build


