name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:
    name: BUILD
    runs-on: ubuntu-latest
    steps:
    - name: Secret Env
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - name: use secret value
      run: echo ${{ PROJECT_ID }} , ${{ FIREBASE_TOKEN }}
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
